name = "tg-image"
compatibility_date = "2023-01-01"
main = "src/index.js"

[vars]
# 可以在这里设置默认环境变量
TG_Bot_Token = "8149346175:AAEPLnJpnrJxtd8zKFGIaKw-m51X53a4Rxk"
TG_Chat_ID = "-4908560346"
JWT_SECRET = "shellshe"

# 注意：在部署前，请先创建这些 KV 命名空间，并将生成的 ID 填入下面的配置中
# 使用以下命令创建 KV 命名空间（Wrangler 4.x 版本）：
# npx wrangler kv namespace create "img_url"
# npx wrangler kv namespace create "users"
#
# 或者使用 npm run create-kv 命令自动创建 KV 命名空间并更新配置

[[kv_namespaces]]
binding = "img_url"
id = "da52b8e6711b48a1ad6abf367e3ae44a"

[[kv_namespaces]]
binding = "users"
id = "35d724932d7f40cba53e6b9c0e7221f2"

[site]
bucket = "./public"
